### ISSUE TITLE
False Link

### ISSUE THREAD

**Issue by BlackYuzia** [Whiletruedoend/Vk-to-telegram-transfer-bot#1]
@Whiletruedoend 
![2018-05-13_215239](https://user-images.githubusercontent.com/25010528/39970665-0f1b76e4-56f8-11e8-8e2c-6e64823a39d7.png)

**Comment by BlackYuzia** [comment]
с ссылка на GIT аналогичная дичь.

**Comment by Whiletruedoend** [comment]
Благодарю, а я и не заметил
_Профикшено_
