### ISSUE TITLE
bot_v

### ISSUE THREAD

**Issue by amazing-c-er** [Whiletruedoend/Vk-to-telegram-transfer-bot#13]
Здравствуйте, во-первых спасибо!
У вас отличная работа получилось!
Можете, пожалуйста, выделить часть кода, где бот только принимает и отправляет текстовые сообщения с обновленными апи и настройками?
Или хотя бы упростить то, что написали, чтоб только text.messages,  а не как у вас (все подробно)
vk>tg
tg<vk
Думаю, поможете)
Заранее спасибо)

**Comment by Whiletruedoend** [comment]
Доброго времени суток!
Немного не понял суть вопроса по поводу обновлённых апи и настроек.
По поводу принятия сообщений, для telegram это: `listener( messages )`, обработка: `checkRedirect_telegram`
Аналогично для вк, принятие: `input_vk()`, обработка: `checkRedirect_vk`

**Comment by amazing-c-er** [comment]
Спасибо, не можете пожалуйста, подсказать в чем может быть проблема...
Получаю из вк сообщения какое-то время, но потом (минут через 15-20) не пересылаются, если я напишу кому-нибудь (или боту) в телеграмме - то будут приходить. После проходит некоторое время, и снова такое - не пересылаются.
Проверяю события через longpoll. Получается так, что я запрашиваю у сервера тг есть ли новое сообщение, а он отвечает мин 20, после нет. Снова отправляю запрос - снова получаю.

**Comment by amazing-c-er** [comment]
Можете посмотреть код, возможно что-нибудь подскажете?
Могу скинуть в телеграм.

**Comment by GenryEden** [comment]
Вообще, это оффтоп, но если вы выложите код на GitHub, то я готов помочь уже в вашем репозитории

**Comment by amazing-c-er** [comment]
Спасибо, у меня пока там немного кода, я только-только пробую.
https://github.com/amazing-c-er/pr_1

> Вообще, это оффтоп, но если вы выложите код на GitHub, то я готов помочь уже в вашем репозитории
