### ISSUE TITLE
Тунели

### ISSUE THREAD

**Issue by m3nd4cium** [Whiletruedoend/Vk-to-telegram-transfer-bot#14]
Посмотрел и видео, и инструкцию здесь и примеры в config.py

тем не менее, туннель работает только в одну сторону из тг в вк (в беседы и в личные чаты)
не смог завести как из под винды так и из под линукса

![Снимок](https://user-images.githubusercontent.com/62580880/108275879-0945ea80-7188-11eb-807a-b962e0dfe594.PNG)

**Comment by Whiletruedoend** [comment]
Вероятно, что-то не так делаешь; Например, на чаты самим с собой оно не реагирует;

**Comment by GenryEden** [comment]
К тому же, учтите, что вся система строится на непрочитанных сообщениях. То есть, если в момент прихода сообщения вы его посмотрели, то оно не перешлется

**Comment by m3nd4cium** [comment]
Спасибо!
Мой котёл до этого не додумался!
Все работает, спасибо, бот - огонь 🔥
