### ISSUE TITLE
Хэлп

### ISSUE THREAD

**Issue by m3nd4cium** [Whiletruedoend/Vk-to-telegram-transfer-bot#17]
![vk transfer](https://user-images.githubusercontent.com/62580880/127702495-b64fa641-eb46-4fe3-b7f0-9cb78896a43b.jpg)

До 25.07 числа все работало на ура, после началась такая история.
Может вк что-то сделал с API?

Скачал заново с репозитория, залил на дедик, ничего не изменилось :(

**Comment by Whiletruedoend** [comment]
Спасибо,
Сейчас не могу проверить работоспособность, в течение недели попробую глянуть в чём может быть проблема

**Comment by Whiletruedoend** [comment]
Не успеваю. Я помню. Как смогу так проверю.

**Comment by m3nd4cium** [comment]
Оке, ждем с нетерпением, спасибо!

**Comment by Whiletruedoend** [comment]
> Оке, ждем с нетерпением, спасибо!

Вроде поправил, надо проверить что всё ок.

**Comment by m3nd4cium** [comment]
Все такая же беда.
![трансфер](https://user-images.githubusercontent.com/62580880/134191042-b60ed7fc-f015-46a7-bfb2-4b45263804c6.jpg)

**Comment by Whiletruedoend** [comment]
У меня:

Python 3.6.9
requests (2.26.0)
urllib3 (1.26.6)
vk-api (11.9.4)

Какие версии библиотек?
Попробуй обновить библиотеку vk_api

**Comment by m3nd4cium** [comment]
Помогло обновление vk_api
Огромное спасибо!
