### ISSUE TITLE
Один вопрос

### ISSUE THREAD

**Issue by Elrut** [Whiletruedoend/Vk-to-telegram-transfer-bot#2]
Привет, есть одна приватная группа в телеге, туда есть доступ только со своего аккаунта. 

Можно ли как то пересылать сообщения в ВК ?

**Comment by Whiletruedoend** [comment]
Нет, для пересылки нужно добавить бота, который бы читал сообщения и отправлял их, со своего аккаунта телеги сделать такое не получится

**Comment by Elrut** [comment]
А у меня получилось это сделать ;)

**Comment by Whiletruedoend** [comment]
Ну и ладно ¯\_(ツ)_/¯
