### ISSUE TITLE
Фото из ВК не приходят в телеграм

### ISSUE THREAD

**Issue by leonatscarlett** [Whiletruedoend/Vk-to-telegram-transfer-bot#3]
Вместо фото приходит только имя отправителя и время отправления. Другие аттачменты приходят.

**Comment by leonatscarlett** [comment]
То же самое, кстати, со стикерами.

**Comment by Whiletruedoend** [comment]
Очень странно, у меня всё работает. Попробуйте перезапустить скрипт, может, поможет...

**Comment by StriletsRilex** [comment]
У меня так же не приходят. Возможно это только с беседами ВК.
