### ISSUE TITLE
Поддержка API версии 5.92

### ISSUE THREAD

**Issue by SkofQQ** [Whiletruedoend/Vk-to-telegram-transfer-bot#5]
Бот перестал работать после обновления vkAPI до версии 5.92. Планируется ли обновление? Спасибо!

**Comment by Whiletruedoend** [comment]
https://vk.com/dev/messages_api
В связи с изменениями доступа к message API, возникли некоторые проблемы при запуске бота. Теперь чтобы всё работало, придётся делать через платформу для ботов, т.е. через сообщества, а раз так, то вся идея о том что для перессылки нужно лишь написать другому человеку канет в небытие, потому что теперь по всей видимости придётся писать сообществу, что != аккаунту бота. Поэтому обновлений скорее всего не будет, т.е. скрипт останется лежать на гитхабе (мало ли кому-то зачем-то нужен будет), но несовместимый с текущей версией API. В общем, опять VK всё перелопатили, и подстраиваться под них каждый раз у меня совершенно нет желания.

**Comment by Whiletruedoend** [comment]
В настоящее время всё работает, просто в config.py должен быть ID приложения, который имеет доступ к API (по-умолчанию он там прописан, поэтому и работает)

**Comment by KOH-I-NOOR** [comment]
ID приложения по-прежнему тот или поменялся?
