### ISSUE TITLE
Unknown API auth error

### ISSUE THREAD

**Issue by ONLY-LIVE-CODE** [Whiletruedoend/Vk-to-telegram-transfer-bot#8]
except vk_api.ApiError as error_msg

does not work

**Comment by CrafterKolyan** [comment]
I think the main problem is that VK closed Messages API for public use:
https://vk.com/dev/messages_api

**Comment by dhvcc** [comment]
> except vk_api.ApiError as error_msg
> 
> does not work

Can you provide us with traceback and some more context?
If the problem was fixes you should close this issue
